// <auto-generated />
namespace FuNDs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class anything : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(anything));
        
        string IMigrationMetadata.Id
        {
            get { return "201510062135276_anything"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
